/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agricare;

import javax.swing.JFrame;

/**
 *
 * @author Akshay
 */
public class mainpage extends javax.swing.JFrame {

   
    public mainpage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        work = new javax.swing.JButton();
        cust = new javax.swing.JButton();
        sell = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        renm = new javax.swing.JButton();
        seed = new javax.swing.JButton();
        order1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("HOME PAGE ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(532, 532, 532)
                .addComponent(jLabel1)
                .addContainerGap(577, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(49, 11, 1270, 80);

        work.setBackground(new java.awt.Color(153, 153, 255));
        work.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        work.setText("WORKERS");
        work.setBorder(null);
        work.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workActionPerformed(evt);
            }
        });
        getContentPane().add(work);
        work.setBounds(590, 120, 139, 60);

        cust.setBackground(new java.awt.Color(153, 153, 255));
        cust.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cust.setText("CUSTOMERS");
        cust.setBorder(null);
        cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custActionPerformed(evt);
            }
        });
        getContentPane().add(cust);
        cust.setBounds(590, 200, 139, 60);

        sell.setBackground(new java.awt.Color(153, 153, 255));
        sell.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sell.setText("SELLERS");
        sell.setBorder(null);
        sell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellActionPerformed(evt);
            }
        });
        getContentPane().add(sell);
        sell.setBounds(590, 280, 139, 60);

        exit.setBackground(new java.awt.Color(153, 153, 255));
        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setText("EXIT");
        exit.setBorder(null);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(590, 590, 139, 61);

        renm.setBackground(new java.awt.Color(153, 153, 255));
        renm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        renm.setText("SEED DEATILS");
        renm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renmActionPerformed(evt);
            }
        });
        getContentPane().add(renm);
        renm.setBounds(590, 510, 139, 61);

        seed.setBackground(new java.awt.Color(153, 153, 255));
        seed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        seed.setText(" SEEDBANK");
        seed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seedActionPerformed(evt);
            }
        });
        getContentPane().add(seed);
        seed.setBounds(590, 360, 139, 61);

        order1.setBackground(new java.awt.Color(153, 153, 255));
        order1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        order1.setText("ORDERS");
        order1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order1ActionPerformed(evt);
            }
        });
        getContentPane().add(order1);
        order1.setBounds(590, 440, 139, 61);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agricare/newimg.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 0, 1270, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void workActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workActionPerformed
        new worker().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_workActionPerformed

    private void custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custActionPerformed
        new home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_custActionPerformed

    private void sellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellActionPerformed
        new seller().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_sellActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        new login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private void seedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seedActionPerformed
        // TODO add your handling code here:
        new seedbank().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_seedActionPerformed

    private void renmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renmActionPerformed
        // TODO add your handling code here:
         new vieww().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_renmActionPerformed

    private void order1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order1ActionPerformed
        // TODO add your handling code here:
         new order().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_order1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cust;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton order1;
    private javax.swing.JButton renm;
    private javax.swing.JButton seed;
    private javax.swing.JButton sell;
    private javax.swing.JButton work;
    // End of variables declaration//GEN-END:variables
}
